// frontend/src/pages/HomePage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { api, fmtDateTime } from '../api';
import { useI18n } from '../composables/useI18n';
import type { TripSearchRow, Wilaya } from '../types';

const { t, lang } = useI18n();
const wilayas = ref<Wilaya[]>([]);
const form = reactive({ from: '', to: '', dateFrom: '', dateTo: '' });
const results = ref<TripSearchRow[] | null>(null);
const total = ref(0);
const busy = ref(false);
const error = ref('');

onMounted(() => {
  api<{ wilayas: Wilaya[] }>('/api/registry/wilayas')
    .then((r) => {
      wilayas.value = r.wilayas;
    })
    .catch((e) => {
      error.value = e instanceof Error ? e.message : String(e);
    });
});

async function search(e: Event): Promise<void> {
  e.preventDefault();
  error.value = '';
  busy.value = true;
  try {
    const q = new URLSearchParams({ from: form.from, to: form.to });
    if (form.dateFrom) q.set('date_from', form.dateFrom);
    if (form.dateTo) q.set('date_to', form.dateTo);
    const r = await api<{ trips: TripSearchRow[]; total: number }>(`/api/trips?${q.toString()}`);
    results.value = r.trips;
    total.value = r.total;
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    busy.value = false;
  }
}

function fmtPrice(trip: TripSearchRow): string {
  return Number(trip.price).toLocaleString(lang.value === 'ar' ? 'ar-DZ' : 'fr-DZ');
}
</script>

<template>
  <section>
    <div class="hero">
      <h1>{{ t('home.title') }}</h1>
      <p>{{ t('home.subtitle') }}</p>
    </div>

    <form class="card search-card" :aria-label="t('home.searchBtn')" @submit="void search($event)">
      <label for="home-from">
        {{ t('home.fromLabel') }}
        <select id="home-from" v-model="form.from" required>
          <option value="">{{ t('home.fromPlaceholder') }}</option>
          <option v-for="w in wilayas" :key="w.id" :value="String(w.id)">{{ String(w.id).padStart(2, '0') }} · {{ w.nom_fr }}</option>
        </select>
      </label>
      <label for="home-to">
        {{ t('home.toLabel') }}
        <select id="home-to" v-model="form.to" required>
          <option value="">{{ t('home.toPlaceholder') }}</option>
          <option v-for="w in wilayas" :key="w.id" :value="String(w.id)" :disabled="String(w.id) === form.from">
            {{ String(w.id).padStart(2, '0') }} · {{ w.nom_fr }}
          </option>
        </select>
      </label>
      <label for="home-date-from">
        {{ t('home.dateFromLabel') }}
        <input id="home-date-from" v-model="form.dateFrom" type="date" :max="form.dateTo || undefined" />
      </label>
      <label for="home-date-to">
        {{ t('home.dateToLabel') }}
        <input id="home-date-to" v-model="form.dateTo" type="date" :min="form.dateFrom || undefined" />
      </label>
      <button class="btn primary" :disabled="busy || !form.from || !form.to || form.from === form.to">
        {{ busy ? t('home.searching') : t('home.searchBtn') }}
      </button>
    </form>

    <p v-if="error" class="alert error" role="alert">{{ error }}</p>

    <div v-if="results !== null" class="results">
      <h2 aria-live="polite">{{ t('home.resultsCount', { count: total, s: total > 1 ? 's' : '' }) }}</h2>
      <p v-if="results.length === 0" class="empty">{{ t('home.noResults') }}</p>
      <div class="grid">
        <router-link v-for="trip in results" :key="trip.id" :to="`/trips/${trip.id}`" class="card trip-card">
          <div class="route">
            <strong>{{ trip.from_wilaya }}</strong>
            <span class="arrow" aria-hidden="true">→</span>
            <strong>{{ trip.to_wilaya }}</strong>
          </div>
          <div class="meta">
            <span>🕒 {{ fmtDateTime(trip.departure_at) }}</span>
            <span>🗺️ {{ trip.trajectory_name }}</span>
          </div>
          <div class="foot">
            <span class="price">{{ fmtPrice(trip) }} {{ trip.currency }}</span>
            <span class="seats">{{ t('home.seatsAvailable', { count: trip.seats_available ?? 0 }) }}</span>
          </div>
        </router-link>
      </div>
    </div>
  </section>
</template>

// frontend/src/pages/HomePage.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api, fmtDateTime } from '../api';
import { useI18n } from '../i18n';
import type { TripSearchRow, Wilaya } from '../types';

export default function HomePage() {
  const { t, lang } = useI18n();
  const [wilayas, setWilayas] = useState<Wilaya[]>([]);
  const [form, setForm] = useState({ from: '', to: '', dateFrom: '', dateTo: '' });
  const [results, setResults] = useState<TripSearchRow[] | null>(null);
  const [total, setTotal] = useState(0);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    api<{ wilayas: Wilaya[] }>('/api/registry/wilayas')
      .then((r) => setWilayas(r.wilayas))
      .catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, []);

  const search = async (e: FormEvent): Promise<void> => {
    e.preventDefault();
    setError('');
    setBusy(true);
    try {
      const q = new URLSearchParams({ from: form.from, to: form.to });
      if (form.dateFrom) q.set('date_from', form.dateFrom);
      if (form.dateTo) q.set('date_to', form.dateTo);
      const r = await api<{ trips: TripSearchRow[]; total: number }>(`/api/trips?${q.toString()}`);
      setResults(r.trips);
      setTotal(r.total);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section>
      <div className="hero">
        <h1>{t('home.title')}</h1>
        <p>{t('home.subtitle')}</p>
      </div>

      <form className="card search-card" onSubmit={(e) => void search(e)} aria-label={t('home.searchBtn')}>
        <label htmlFor="home-from">
          {t('home.fromLabel')}
          <select
            id="home-from"
            required
            value={form.from}
            onChange={(e) => setForm({ ...form, from: e.target.value })}
          >
            <option value="">{t('home.fromPlaceholder')}</option>
            {wilayas.map((w) => (
              <option key={w.id} value={w.id}>
                {String(w.id).padStart(2, '0')} · {w.nom_fr}
              </option>
            ))}
          </select>
        </label>
        <label htmlFor="home-to">
          {t('home.toLabel')}
          <select id="home-to" required value={form.to} onChange={(e) => setForm({ ...form, to: e.target.value })}>
            <option value="">{t('home.toPlaceholder')}</option>
            {wilayas.map((w) => (
              <option key={w.id} value={w.id} disabled={String(w.id) === form.from}>
                {String(w.id).padStart(2, '0')} · {w.nom_fr}
              </option>
            ))}
          </select>
        </label>
        <label htmlFor="home-date-from">
          {t('home.dateFromLabel')}
          <input
            id="home-date-from"
            type="date"
            value={form.dateFrom}
            max={form.dateTo || undefined}
            onChange={(e) => setForm({ ...form, dateFrom: e.target.value })}
          />
        </label>
        <label htmlFor="home-date-to">
          {t('home.dateToLabel')}
          <input
            id="home-date-to"
            type="date"
            value={form.dateTo}
            min={form.dateFrom || undefined}
            onChange={(e) => setForm({ ...form, dateTo: e.target.value })}
          />
        </label>
        <button className="btn primary" disabled={busy || !form.from || !form.to || form.from === form.to}>
          {busy ? t('home.searching') : t('home.searchBtn')}
        </button>
      </form>

      {error && (
        <p className="alert error" role="alert">
          {error}
        </p>
      )}

      {results !== null && (
        <div className="results">
          <h2 aria-live="polite">{t('home.resultsCount', { count: total, s: total > 1 ? 's' : '' })}</h2>
          {results.length === 0 && <p className="empty">{t('home.noResults')}</p>}
          <div className="grid">
            {results.map((trip) => (
              <Link key={trip.id} to={`/trips/${trip.id}`} className="card trip-card">
                <div className="route">
                  <strong>{trip.from_wilaya}</strong>
                  <span className="arrow" aria-hidden="true">
                    →
                  </span>
                  <strong>{trip.to_wilaya}</strong>
                </div>
                <div className="meta">
                  <span>🕒 {fmtDateTime(trip.departure_at)}</span>
                  <span>🗺️ {trip.trajectory_name}</span>
                </div>
                <div className="foot">
                  <span className="price">
                    {Number(trip.price).toLocaleString(lang === 'ar' ? 'ar-DZ' : 'fr-DZ')} {trip.currency}
                  </span>
                  <span className="seats">{t('home.seatsAvailable', { count: trip.seats_available ?? 0 })}</span>
                </div>
              </Link>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}
