// frontend/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api, setSessionToken } from '../api';
import { useAuth } from '../composables/useAuth';
import { useI18n } from '../composables/useI18n';

interface Challenge {
  otp_required: true;
  otp_token: string;
  expires_in: number;
  channel: 'email' | 'sms';
  can_use_sms: boolean;
  dev_code?: string;
}

const { t } = useI18n();
const route = useRoute();
const next = (route.query.next as string) ?? '/';
const router = useRouter();
const { refresh } = useAuth();

const step = ref<'password' | 'otp'>('password');
const email = ref('');
const password = ref('');
const code = ref('');
const challenge = ref<Challenge | null>(null);
const busy = ref(false);
const error = ref('');

async function submitPassword(e: Event): Promise<void> {
  e.preventDefault();
  error.value = '';
  busy.value = true;
  try {
    const r = await api<Challenge>('/api/auth/login', { method: 'POST', body: { email: email.value, password: password.value } });
    challenge.value = r;
    step.value = 'otp';
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    busy.value = false;
  }
}

async function submitCode(e: Event): Promise<void> {
  e.preventDefault();
  error.value = '';
  busy.value = true;
  try {
    const r = await api<{ user: unknown; token: string }>('/api/auth/verify-2fa', {
      method: 'POST',
      body: { otp_token: challenge.value?.otp_token, code: code.value },
    });
    setSessionToken(r.token);
    await refresh();
    void router.push(next);
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    busy.value = false;
  }
}

async function resend(channel?: 'email' | 'sms'): Promise<void> {
  error.value = '';
  busy.value = true;
  try {
    if (challenge.value) {
      challenge.value = await api<Challenge>('/api/auth/resend-2fa', {
        method: 'POST',
        body: { otp_token: challenge.value.otp_token, channel },
      });
    }
    code.value = '';
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    busy.value = false;
  }
}

function onCodeInput(e: Event): void {
  code.value = (e.target as HTMLInputElement).value.replace(/\D/g, '');
}
</script>

<template>
  <section class="narrow">
    <h1>{{ t('login.title') }}</h1>
    <form v-if="step === 'password'" class="card" @submit="void submitPassword($event)">
      <label for="login-email">
        {{ t('login.email') }}
        <input id="login-email" v-model="email" type="email" required :placeholder="t('login.emailPlaceholder')" autocomplete="email" />
      </label>
      <label for="login-password">
        {{ t('login.password') }}
        <input id="login-password" v-model="password" type="password" required autocomplete="current-password" />
      </label>
      <button class="btn primary wide" :disabled="busy">{{ busy ? t('login.verifying') : t('login.continueBtn') }}</button>
      <p class="muted center">
        {{ t('login.noAccount') }} <router-link to="/register">{{ t('login.createAccount') }}</router-link>
      </p>
    </form>
    <form v-else class="card" @submit="void submitCode($event)">
      <p class="muted">{{ challenge?.channel === 'sms' ? t('login.codeSentToSms') : t('login.codeSentTo', { email }) }}</p>
      <p v-if="challenge?.dev_code" class="alert info" role="status">{{ t('login.devModeCode', { code: challenge.dev_code }) }}</p>
      <label for="login-otp">
        {{ t('login.verificationCode') }}
        <input
          id="login-otp"
          :value="code"
          inputmode="numeric"
          pattern="[0-9]{6}"
          maxlength="6"
          required
          placeholder="······"
          class="otp-input"
          autocomplete="one-time-code"
          @input="onCodeInput"
        />
      </label>
      <button class="btn primary wide" :disabled="busy || code.length !== 6">{{ busy ? t('login.verifying') : t('login.submit') }}</button>
      <button type="button" class="btn ghost wide" :disabled="busy" @click="void resend()">{{ t('login.resend') }}</button>
      <button
        v-if="challenge?.can_use_sms"
        type="button"
        class="btn ghost wide"
        :disabled="busy"
        @click="void resend(challenge!.channel === 'sms' ? 'email' : 'sms')"
      >
        {{ challenge.channel === 'sms' ? t('login.useEmailInstead') : t('login.useSmsInstead') }}
      </button>
    </form>
    <p v-if="error" class="alert error" role="alert">{{ error }}</p>
  </section>
</template>

// frontend/src/pages/LoginPage.tsx
import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api, setSessionToken } from '../api';
import { useAuth } from '../auth';
import { useI18n } from '../i18n';

interface Challenge {
  otp_required: true;
  otp_token: string;
  expires_in: number;
  channel: 'email' | 'sms';
  can_use_sms: boolean;
  dev_code?: string;
}

export default function LoginPage() {
  const { t } = useI18n();
  const [searchParams] = useSearchParams();
  const next = searchParams.get('next') ?? '/';
  const navigate = useNavigate();
  const { refresh } = useAuth();

  const [step, setStep] = useState<'password' | 'otp'>('password');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [code, setCode] = useState('');
  const [challenge, setChallenge] = useState<Challenge | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const submitPassword = async (e: FormEvent): Promise<void> => {
    e.preventDefault();
    setError('');
    setBusy(true);
    try {
      const r = await api<Challenge>('/api/auth/login', { method: 'POST', body: { email, password } });
      setChallenge(r);
      setStep('otp');
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  const submitCode = async (e: FormEvent): Promise<void> => {
    e.preventDefault();
    setError('');
    setBusy(true);
    try {
      const r = await api<{ user: unknown; token: string }>('/api/auth/verify-2fa', {
        method: 'POST',
        body: { otp_token: challenge?.otp_token, code },
      });
      setSessionToken(r.token);
      await refresh();
      navigate(next);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  const resend = async (channel?: 'email' | 'sms'): Promise<void> => {
    setError('');
    setBusy(true);
    try {
      if (challenge)
        setChallenge(
          await api<Challenge>('/api/auth/resend-2fa', { method: 'POST', body: { otp_token: challenge.otp_token, channel } }),
        );
      setCode('');
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="narrow">
      <h1>{t('login.title')}</h1>
      {step === 'password' ? (
        <form className="card" onSubmit={(e) => void submitPassword(e)}>
          <label htmlFor="login-email">
            {t('login.email')}
            <input
              id="login-email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={t('login.emailPlaceholder')}
              autoComplete="email"
            />
          </label>
          <label htmlFor="login-password">
            {t('login.password')}
            <input
              id="login-password"
              type="password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
            />
          </label>
          <button className="btn primary wide" disabled={busy}>
            {busy ? t('login.verifying') : t('login.continueBtn')}
          </button>
          <p className="muted center">
            {t('login.noAccount')} <Link to="/register">{t('login.createAccount')}</Link>
          </p>
        </form>
      ) : (
        <form className="card" onSubmit={(e) => void submitCode(e)}>
          <p className="muted">
            {challenge?.channel === 'sms' ? t('login.codeSentToSms') : t('login.codeSentTo', { email })}
          </p>
          {challenge?.dev_code && (
            <p className="alert info" role="status">
              {t('login.devModeCode', { code: challenge.dev_code })}
            </p>
          )}
          <label htmlFor="login-otp">
            {t('login.verificationCode')}
            <input
              id="login-otp"
              inputMode="numeric"
              pattern="[0-9]{6}"
              maxLength={6}
              required
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
              placeholder="······"
              className="otp-input"
              autoComplete="one-time-code"
            />
          </label>
          <button className="btn primary wide" disabled={busy || code.length !== 6}>
            {busy ? t('login.verifying') : t('login.submit')}
          </button>
          <button type="button" className="btn ghost wide" disabled={busy} onClick={() => void resend()}>
            {t('login.resend')}
          </button>
          {challenge?.can_use_sms && (
            <button
              type="button"
              className="btn ghost wide"
              disabled={busy}
              onClick={() => void resend(challenge.channel === 'sms' ? 'email' : 'sms')}
            >
              {challenge.channel === 'sms' ? t('login.useEmailInstead') : t('login.useSmsInstead')}
            </button>
          )}
        </form>
      )}
      {error && (
        <p className="alert error" role="alert">
          {error}
        </p>
      )}
    </section>
  );
}
